services:
    MagicSunday\Memories\Clusterer\TimeSimilarityStrategy:
        arguments:
            $maxGapSeconds: '%memories.cluster.time_gap_seconds%'
            $minItems: 5

    MagicSunday\Memories\Clusterer\LocationSimilarityStrategy:
        arguments:
            $radiusMeters: '%memories.cluster.geo_radius_m%'
            $minItems: 5
            $maxSpanHours: 24

    MagicSunday\Memories\Clusterer\DeviceSimilarityStrategy:
        arguments:
            $minItems: 5

    MagicSunday\Memories\Clusterer\PhashSimilarityStrategy:
        arguments:
            $maxHamming: 6
            $minItems: 2

    # --- Composition & session heuristics ---
    MagicSunday\Memories\Clusterer\BurstClusterStrategy:
        arguments:
            $maxGapSeconds: 90
            $maxMoveMeters: 50.0
            $minItems: 3

    MagicSunday\Memories\Clusterer\PhotoMotifClusterStrategy:
        arguments:
            $sessionGapSeconds: 172800   # 48h
            $minItems: 10

    MagicSunday\Memories\Clusterer\CrossDimensionClusterStrategy:
        arguments:
            $timeGapSeconds: 7200        # 2h
            $radiusMeters: 150.0
            $minItems: 6

    MagicSunday\Memories\Clusterer\PanoramaClusterStrategy:
        arguments:
            $minAspect: 2.4
            $sessionGapSeconds: 10800   # 3h
            $minItems: 3

    MagicSunday\Memories\Clusterer\PanoramaOverYearsClusterStrategy:
        arguments:
            $minAspect: 2.4
            $perYearMin: 3
            $minYears: 3
            $minItemsTotal: 15

    MagicSunday\Memories\Clusterer\PortraitOrientationClusterStrategy:
        arguments:
            $minPortraitRatio: 1.2
            $sessionGapSeconds: 7200      # 2h
            $minItems: 4

    MagicSunday\Memories\Clusterer\VideoStoriesClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItems: 2

    # --- Daily life & home rituals ---
    MagicSunday\Memories\Clusterer\DayAlbumClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItems: 8

    MagicSunday\Memories\Clusterer\MorningCoffeeClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $sessionGapSeconds: 5400      # 1.5h
            $radiusMeters: 200.0
            $minItems: 3

    MagicSunday\Memories\Clusterer\AtHomeWeekendClusterStrategy:
        arguments:
            $homeLat: '%env(float:MEMORIES_HOME_LAT)%'
            $homeLon: '%env(float:MEMORIES_HOME_LON)%'
            $homeRadiusMeters: 300.0
            $minHomeShare: 0.7
            $minItemsPerDay: 4
            $minItemsTotal: 6
            $timezone: 'Europe/Berlin'

    MagicSunday\Memories\Clusterer\AtHomeWeekdayClusterStrategy:
        arguments:
            $homeLat: '%env(float:MEMORIES_HOME_LAT)%'
            $homeLon: '%env(float:MEMORIES_HOME_LON)%'
            $homeRadiusMeters: 300.0
            $minHomeShare: 0.7
            $minItemsPerDay: 4
            $minItemsTotal: 8
            $timezone: 'Europe/Berlin'

    MagicSunday\Memories\Clusterer\DiningOutClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $sessionGapSeconds: 7200   # 2h
            $radiusMeters: 250.0
            $minItems: 4

    # --- Social celebrations & people ---
    MagicSunday\Memories\Clusterer\AnniversaryClusterStrategy: ~

    MagicSunday\Memories\Clusterer\PersonCohortClusterStrategy:
        arguments:
            $minPersons: 2
            $minItems: 5
            $windowDays: 14

    MagicSunday\Memories\Clusterer\KidsBirthdayPartyClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $sessionGapSeconds: 10800     # 3h
            $radiusMeters: 250.0
            $minItems: 6

    MagicSunday\Memories\Clusterer\PetMomentsClusterStrategy:
        arguments:
            $sessionGapSeconds: 7200   # 2h
            $minItems: 10

    MagicSunday\Memories\Clusterer\HolidayEventClusterStrategy:
        arguments:
            $minItems: 8

    # --- Special outings & events ---
    MagicSunday\Memories\Clusterer\NightlifeEventClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $timeGapSeconds: 10800       # 3h
            $radiusMeters: 300.0
            $minItems: 5

    MagicSunday\Memories\Clusterer\SportsEventClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $sessionGapSeconds: 10800     # 3h
            $radiusMeters: 500.0
            $minItems: 6
            $preferWeekend: true

    MagicSunday\Memories\Clusterer\FestivalSummerClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $sessionGapSeconds: 10800     # 3h
            $radiusMeters: 600.0
            $minItems: 10

    MagicSunday\Memories\Clusterer\NewYearEveClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $startHour: 20
            $endHour: 2
            $minItems: 6

    # --- Travel & outdoor adventures ---
    MagicSunday\Memories\Clusterer\WeekendTripClusterStrategy:
        arguments:
            $minAwayKm: 80.0
            $minNights: 1

    MagicSunday\Memories\Clusterer\WeekendGetawaysOverYearsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minNights: 1
            $maxNights: 3
            $minItemsPerDay: 4
            $minYears: 3
            $minItemsTotal: 24

    MagicSunday\Memories\Clusterer\LongTripClusterStrategy:
        arguments:
            $homeLat: '%env(float:MEMORIES_HOME_LAT)%'
            $homeLon: '%env(float:MEMORIES_HOME_LON)%'
            $minAwayKm: 150.0
            $minNights: 3

    MagicSunday\Memories\Clusterer\RoadTripClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minDailyKm: 120.0
            $minGpsSamplesPerDay: 8
            $minNights: 3
            $minItemsTotal: 40

    MagicSunday\Memories\Clusterer\HikeAdventureClusterStrategy:
        arguments:
            $sessionGapSeconds: 10800     # 3h
            $minDistanceKm: 6.0
            $minItems: 6
            $minItemsNoGps: 12

    MagicSunday\Memories\Clusterer\CampingTripClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItemsPerDay: 3
            $minNights: 2
            $maxNights: 14
            $minItemsTotal: 20

    MagicSunday\Memories\Clusterer\CampingOverYearsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItemsPerDay: 3
            $minNights: 2
            $maxNights: 14
            $minYears: 3
            $minItemsTotal: 24

    MagicSunday\Memories\Clusterer\BeachOverYearsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItemsPerDay: 6
            $minYears: 3
            $minItemsTotal: 24

    MagicSunday\Memories\Clusterer\SnowVacationOverYearsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItemsPerDay: 4
            $minNights: 3
            $maxNights: 14
            $minYears: 3
            $minItemsTotal: 30

    MagicSunday\Memories\Clusterer\TransitTravelDayClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minTravelKm: 60.0
            $minGpsSamples: 5

    # --- Place-based explorations ---
    MagicSunday\Memories\Clusterer\FirstVisitPlaceClusterStrategy:
        arguments:
            $gridDegrees: 0.01
            $timezone: 'Europe/Berlin'
            $minItemsPerDay: 4
            $minNights: 0
            $maxNights: 3
            $minItemsTotal: 8

    MagicSunday\Memories\Clusterer\SignificantPlaceClusterStrategy:
        arguments:
            $gridDegrees: 0.01
            $minVisitDays: 3
            $minItemsTotal: 20

    MagicSunday\Memories\Clusterer\CityscapeNightClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $sessionGapSeconds: 7200      # 2h
            $radiusMeters: 350.0
            $minItems: 5

    MagicSunday\Memories\Clusterer\ZooAquariumClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $sessionGapSeconds: 7200      # 2h
            $radiusMeters: 400.0
            $minItems: 5

    MagicSunday\Memories\Clusterer\ZooAquariumOverYearsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItemsPerDay: 5
            $minYears: 3
            $minItemsTotal: 18

    MagicSunday\Memories\Clusterer\MuseumOverYearsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItemsPerDay: 5
            $minYears: 3
            $minItemsTotal: 18

    # --- Weather & seasonal highlights ---
    MagicSunday\Memories\Clusterer\SeasonClusterStrategy:
        arguments:
            $minItems: 20

    MagicSunday\Memories\Clusterer\SeasonOverYearsClusterStrategy:
        arguments:
            $minYears: 3
            $minItems: 30

    MagicSunday\Memories\Clusterer\SunnyDayClusterStrategy:
        arguments:
            $minAvgSunScore: 0.65
            $minItemsPerDay: 6
            $minHintsPerDay: 3
            $timezone: 'Europe/Berlin'

    MagicSunday\Memories\Clusterer\RainyDayClusterStrategy:
        arguments:
            $minAvgRainProb: 0.6
            $minItemsPerDay: 6
            $timezone: 'Europe/Berlin'

    MagicSunday\Memories\Clusterer\SnowDayClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $sessionGapSeconds: 7200      # 2h
            $minItems: 6

    MagicSunday\Memories\Clusterer\GoldenHourClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $morningHours:
                - 6
                - 7
                - 8
            $eveningHours:
                - 18
                - 19
                - 20
            $sessionGapSeconds: 5400
            $minItems: 5

    # --- Temporal retrospectives ---
    MagicSunday\Memories\Clusterer\ThisMonthOverYearsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minYears: 3
            $minItems: 24
            $minDistinctDays: 8

    MagicSunday\Memories\Clusterer\OnThisDayOverYearsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $windowDays: 0
            $minYears: 3
            $minItems: 12

    MagicSunday\Memories\Clusterer\OneYearAgoClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $windowDays: 3
            $minItems: 8

    MagicSunday\Memories\Clusterer\YearInReviewClusterStrategy:
        arguments:
            $minItems: 150
            $minDistinctMonths: 5

    MagicSunday\Memories\Clusterer\MonthlyHighlightsClusterStrategy:
        arguments:
            $timezone: 'Europe/Berlin'
            $minItems: 40
            $minDistinctDays: 10
