########################################
# Projekt-Parameter (zentral steuerbar)
########################################
parameters:
    memories.index.image_ext: ['jpg','jpeg','jpe','jxl','avif','heic','heif','png','webp','gif','bmp','tiff','tif','cr2','cr3','nef','arw','rw2','raf','dng']
    memories.index.video_ext: []
#    memories.index.video_ext: ['mp4','m4v','mov','3gp','3g2','avi','mkv','webm']

    # Hash Defaults
    memories.hash.dct_sample: 32
    memories.hash.lowfreq: 8

    # Thumbnail-Größen (px)
    memories.thumbnail_sizes: [320, 1024]

    # Consolidation Defaults
    memories.cluster.consolidate.min_score: 0.35      # je nach Scorer-Skala
    memories.cluster.consolidate.min_size: 4
    memories.cluster.consolidate.drop_jaccard: 0.80   # >=80% Overlap -> unterdrücken
    memories.cluster.consolidate.per_media_cap: 1     # jedes Bild max. 1 Cluster
    memories.cluster.consolidate.algo_priority:
        cross_dimension:   110
        weekend_trip:      105
        phash_similarity:  100
        location_similarity: 95
        time_similarity:    90
        season:             85
        holiday_event:      85
        video_stories:      80
        nightlife_event:    75
        photo_motif:        75
        burst:              70
        anniversary:        65
        device_similarity:  60
        person_cohort:      55

    # Scoring Defaults
    memories.score.min_valid_year: 1995
    memories.score.time_range.min_samples: 3
    memories.score.time_range.min_coverage: 0.6
