placeCategories:
    beach:
        - beach
        - coast
        - bay
        - riviera
    mountains:
        - alps
        - dolomites
        - himalaya
        - rockies
    city:
        - berlin
        - paris
        - london
        - new york
    nature:
        - forest
        - park
        - lake
        - national park

presets:
    # --- Season + City ---
    - name: "Spring City Trip"
      priority: 100
      season: "Spring"
      placeHint: "city"
      template: "Spring in {city}"

    - name: "Summer City Trip"
      priority: 100
      season: "Summer"
      placeHint: "city"
      template: "Summer days in {city}"

    # --- Country fallback ---
    - name: "Winter in Country"
      priority: 90
      season: "Winter"
      template: "Winter in {country}"

    - name: "Summer in Country"
      priority: 90
      season: "Summer"
      template: "Summer in {country}"

    # --- Category based ---
    - name: "Beach Vacation"
      priority: 80
      placeHint: "beach"
      template: "Relaxing days at the {category}"

    - name: "Mountain Adventure"
      priority: 80
      placeHint: "mountains"
      template: "Adventure in the {category}"

    # --- General fallback ---
    - name: "Seasonal Memory"
      priority: 10
      template: "{season} memories"

    - name: "Default Memory"
      priority: 0
      template: "My Photo Memories"
