parameters:
    memories.selection.default_profile: 'highlights'
    memories.selection.profiles:
        vacation:
            target_total: 60
            minimum_total: 36
            max_per_day: 5
            time_slot_hours: 4
            min_spacing_seconds: 2400
            phash_min_hamming: 9
            max_per_staypoint: 2
            quality_floor: 0.54
            video_bonus: 0.22
            face_bonus: 0.32
            selfie_penalty: 0.25
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.25
        location:
            target_total: 45
            minimum_total: 27
            max_per_day: 4
            time_slot_hours: 4
            min_spacing_seconds: 2400
            phash_min_hamming: 10
            max_per_staypoint: 2
            quality_floor: 0.52
            video_bonus: 0.2
            face_bonus: 0.3
            selfie_penalty: 0.28
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.18
        scene:
            target_total: 40
            minimum_total: 24
            max_per_day: 4
            time_slot_hours: 4
            min_spacing_seconds: 2400
            phash_min_hamming: 10
            max_per_staypoint: 2
            quality_floor: 0.5
            video_bonus: 0.18
            face_bonus: 0.26
            selfie_penalty: 0.26
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.15
        device:
            target_total: 36
            minimum_total: 24
            max_per_day: 4
            time_slot_hours: 4
            min_spacing_seconds: 2400
            phash_min_hamming: 10
            max_per_staypoint: 2
            quality_floor: 0.5
            video_bonus: 0.18
            face_bonus: 0.24
            selfie_penalty: 0.25
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.15
        over_years:
            target_total: 32
            minimum_total: 24
            max_per_day: 4
            time_slot_hours: 3
            min_spacing_seconds: 2400
            phash_min_hamming: 10
            max_per_staypoint: 2
            quality_floor: 0.55
            video_bonus: 0.22
            face_bonus: 0.32
            selfie_penalty: 0.25
            max_per_year: 3
            max_per_bucket: 3
            video_heavy_bonus: 0.12
        highlights:
            target_total: 30
            minimum_total: 24
            max_per_day: 4
            time_slot_hours: 4
            min_spacing_seconds: 2400
            phash_min_hamming: 10
            max_per_staypoint: 2
            quality_floor: 0.56
            video_bonus: 0.35
            face_bonus: 0.35
            selfie_penalty: 0.25
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.28
        panorama:
            target_total: 26
            minimum_total: 24
            max_per_day: 3
            time_slot_hours: 4
            min_spacing_seconds: 2400
            phash_min_hamming: 10
            max_per_staypoint: 2
            quality_floor: 0.52
            video_bonus: 0.24
            face_bonus: 0.28
            selfie_penalty: 0.25
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.2
        nightlife:
            target_total: 24
            minimum_total: 24
            max_per_day: 4
            time_slot_hours: 3
            min_spacing_seconds: 2400
            phash_min_hamming: 9
            max_per_staypoint: 2
            quality_floor: 0.5
            video_bonus: 0.28
            face_bonus: 0.3
            selfie_penalty: 0.25
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.22
        video:
            target_total: 26
            minimum_total: 24
            max_per_day: 4
            time_slot_hours: 4
            min_spacing_seconds: 2400
            phash_min_hamming: 9
            max_per_staypoint: 2
            quality_floor: 0.5
            video_bonus: 0.4
            face_bonus: 0.35
            selfie_penalty: 0.22
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.32
    memories.selection.algorithm_profiles:
        vacation: 'vacation'
        transit_travel_day: 'vacation'
        at_home_weekend: 'vacation'
        weekend_getaways_over_years: 'vacation'
        significant_place: 'location'
        location_similarity: 'location'
        first_visit_place: 'location'
        season: 'scene'
        day_album: 'over_years'
        one_year_ago: 'over_years'
        on_this_day_over_years: 'over_years'
        this_month_over_years: 'over_years'
        season_over_years: 'over_years'
        panorama_over_years: 'over_years'
        anniversary: 'over_years'
        device_similarity: 'device'
        cross_dimension: 'device'
        portrait_orientation: 'scene'
        burst: 'scene'
        phash_similarity: 'scene'
        time_similarity: 'scene'
        year_in_review: 'highlights'
        monthly_highlights: 'highlights'
        holiday_event: 'highlights'
        people_cohort: 'highlights'
        video_stories: 'video'
        golden_hour: 'panorama'
        nightlife_event: 'nightlife'
        panorama: 'panorama'
        new_year_eve: 'nightlife'
