parameters:
    memories.selection.default_profile: 'highlights'
    memories.selection.profiles:
        vacation:
            target_total: 60
            minimum_total: 14
            max_per_day: 8
            time_slot_hours: 3.0
            min_spacing_seconds: 105
            phash_min_hamming: 18
            max_per_staypoint: 3
            quality_floor: 0.25
            video_bonus: 0.6
            face_bonus: 0.4
            selfie_penalty: 0.15
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.25
        location:
            target_total: 45
            minimum_total: 12
            max_per_day: 6
            time_slot_hours: 2.5
            min_spacing_seconds: 75
            phash_min_hamming: 16
            max_per_staypoint: 2
            quality_floor: 0.28
            video_bonus: 0.3
            face_bonus: 0.25
            selfie_penalty: 0.12
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.15
        scene:
            target_total: 40
            minimum_total: 10
            max_per_day: 5
            time_slot_hours: 4.0
            min_spacing_seconds: 150
            phash_min_hamming: 14
            max_per_staypoint: 2
            quality_floor: 0.3
            video_bonus: 0.2
            face_bonus: 0.2
            selfie_penalty: 0.1
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.1
        device:
            target_total: 36
            minimum_total: 10
            max_per_day: 5
            time_slot_hours: 4.0
            min_spacing_seconds: 150
            phash_min_hamming: 18
            max_per_staypoint: 3
            quality_floor: 0.27
            video_bonus: 0.15
            face_bonus: 0.1
            selfie_penalty: 0.08
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.1
        over_years:
            target_total: 32
            minimum_total: 9
            max_per_day: 2
            time_slot_hours: null
            min_spacing_seconds: 120
            phash_min_hamming: 16
            max_per_staypoint: 2
            quality_floor: 0.3
            video_bonus: 0.25
            face_bonus: 0.25
            selfie_penalty: 0.1
            max_per_year: 3
            max_per_bucket: 3
            video_heavy_bonus: 0.1
        highlights:
            target_total: 28
            minimum_total: 12
            max_per_day: 4
            time_slot_hours: 3.5
            min_spacing_seconds: 150
            phash_min_hamming: 20
            max_per_staypoint: 3
            quality_floor: 0.4
            video_bonus: 0.7
            face_bonus: 0.5
            selfie_penalty: 0.12
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.3
        panorama:
            target_total: 22
            minimum_total: 8
            max_per_day: 3
            time_slot_hours: 3.0
            min_spacing_seconds: 105
            phash_min_hamming: 18
            max_per_staypoint: 2
            quality_floor: 0.32
            video_bonus: 0.25
            face_bonus: 0.2
            selfie_penalty: 0.1
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.2
        nightlife:
            target_total: 24
            minimum_total: 8
            max_per_day: 4
            time_slot_hours: 2.0
            min_spacing_seconds: 120
            phash_min_hamming: 14
            max_per_staypoint: 3
            quality_floor: 0.28
            video_bonus: 0.35
            face_bonus: 0.25
            selfie_penalty: 0.1
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.25
        video:
            target_total: 26
            minimum_total: 10
            max_per_day: 4
            time_slot_hours: 3.0
            min_spacing_seconds: 135
            phash_min_hamming: 18
            max_per_staypoint: 3
            quality_floor: 0.33
            video_bonus: 0.75
            face_bonus: 0.45
            selfie_penalty: 0.12
            max_per_year: null
            max_per_bucket: null
            video_heavy_bonus: 0.35
    memories.selection.algorithm_profiles:
        vacation: 'vacation'
        transit_travel_day: 'vacation'
        at_home_weekend: 'vacation'
        weekend_getaways_over_years: 'vacation'
        significant_place: 'location'
        location_similarity: 'location'
        first_visit_place: 'location'
        season: 'scene'
        day_album: 'over_years'
        one_year_ago: 'over_years'
        on_this_day_over_years: 'over_years'
        this_month_over_years: 'over_years'
        season_over_years: 'over_years'
        panorama_over_years: 'over_years'
        anniversary: 'over_years'
        device_similarity: 'device'
        cross_dimension: 'device'
        portrait_orientation: 'scene'
        burst: 'scene'
        phash_similarity: 'scene'
        time_similarity: 'scene'
        year_in_review: 'highlights'
        monthly_highlights: 'highlights'
        holiday_event: 'highlights'
        people_cohort: 'highlights'
        video_stories: 'video'
        golden_hour: 'panorama'
        nightlife_event: 'nightlife'
        panorama: 'panorama'
        new_year_eve: 'nightlife'
